version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blulog-app
    container_name: app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOSTNAME=db
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    # entrypoint: ["/usr/src/app/wait-for.sh", "db:27017", "--", "npm", "start"]
    entrypoint: ["/usr/src/app/wait-for.sh", "db:27017", "--", "npm", "run", "dev"]


  db:
    image: mongo:6.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
